services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    pull_policy: never

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    pull_policy: never
